ZhouliProject/ZhouliSystem/Components/NavigationViewComponent.cs
using DInjectionProvider;
using Microsoft.AspNetCore.Mvc;
using Zhouli.BLL.Interface;
using ZhouliSystem.Data;
using ZhouliSystem.Filters;

namespace ZhouliSystem.Components
{
    [ViewComponent(Name = "Navigation")]
    [VerificationLogin]
    public class NavigationViewComponent : ViewComponent
    {
        private readonly WholeInjection injection;
        public NavigationViewComponent(WholeInjection injection)
        {
            this.injection = injection;
        }
        public IViewComponentResult Invoke()
        {
            var user = injection.GetT<UserAccount>().GetUserInfo();
            var MenuDto = injection.GetT<ISysMenuBLL>().GetMenusBy(user).Data;
            return View(MenuDto);
        }
    }
}

ZhouliProject/ZhouliSystem/Controllers/HomeController.cs
#region 版权声明
/**************************************************************** 
 * 作    者：周黎 
 * CLR 版本：4.0.30319.42000 
 * 创建时间：2018/6/8 21:41:11 
 * 当前版本：1.0.0.1 
 *  
 * 描述说明： 
 * 
 * 修改历史： 
 * 
***************************************************************** 
 * Copyright @ ZhouLi 2018 All rights reserved 
 *┌──────────────────────────────────┐
 *│　此技术信息周黎的机密信息，未经本人书面同意禁止向第三方披露．　│
 *│　版权所有：周黎 　　　　　　　　　　　　　　│
 *└──────────────────────────────────┘
*****************************************************************/
#endregion
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ZhouliSystem.Models;
using Zhouli.DbEntity.Models;
using DInjectionProvider;
using ZhouliSystem.Filters;
using ZhouliSystem.Data;
using Zhouli.BLL.Interface;

namespace ZhouliSystem.Controllers
{
    [VerificationLogin]
    public class HomeController : Controller
    {
        private readonly WholeInjection injection;
        public HomeController(WholeInjection injection)
        {
            this.injection = injection;
        }
        public IActionResult Index()
        {
            var User = injection.GetT<UserAccount>().GetUserInfo();
            return View(User);
        }
        public IActionResult Welcome()
        {
            return View();
        }
       
    }
}

ZhouliProject/ZhouliSystem/Views/Home/Index.cshtml
@model Zhouli.DbEntity.Models.SysUser
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "后台管理系统主页";

}
<div class="layui-layout layui-layout-admin">
    <!-- 顶部 -->
    <div class="layui-header header">
        <div class="layui-main mag0">
            <a href="#" class="logo">周黎的后台</a>
            <!-- 显示/隐藏菜单 -->
            <a href="javascript:;" class="seraph hideMenu icon-caidan"></a>
            <!-- 顶级菜单 -->
            <ul class="layui-nav mobileTopLevelMenus" mobile>
                <li class="layui-nav-item" data-menu="contentManagement">
                    <a href="javascript:;"><i class="seraph icon-caidan"></i><cite>layuiCMS</cite></a>
                    <dl class="layui-nav-child">
                        <dd class="layui-this" data-menu="contentManagement"><a href="javascript:;"><i class="layui-icon" data-icon="&#xe63c;">&#xe63c;</i><cite>内容管理</cite></a></dd>
                        <dd data-menu="memberCenter"><a href="javascript:;"><i class="seraph icon-icon10" data-icon="icon-icon10"></i><cite>用户中心</cite></a></dd>
                        <dd data-menu="systemeSttings"><a href="javascript:;"><i class="layui-icon" data-icon="&#xe620;">&#xe620;</i><cite>系统设置</cite></a></dd>
                        <dd data-menu="seraphApi"><a href="javascript:;"><i class="layui-icon" data-icon="&#xe705;">&#xe705;</i><cite>使用文档</cite></a></dd>
                    </dl>
                </li>
            </ul>
            <!-- 顶部右侧菜单 -->
            <ul class="layui-nav top_menu">
                @*<li class="layui-nav-item lockcms" pc>
                    <a href="javascript:;"><i class="seraph icon-lock"></i><cite>锁屏</cite></a>
                </li>*@
                <li class="layui-nav-item" id="userInfo">
                    <a href="javascript:;"><img src="@Model.UserAvatar" class="layui-nav-img userAvatar" id="userAvatar" width="35" height="35"><cite class="adminName">@Model.UserNikeName</cite></a>
                    <dl class="layui-nav-child">
                        <dd><a href="javascript:;" data-url="/User/UserInfo"><i class="seraph icon-ziliao" data-icon="icon-ziliao"></i><cite>个人资料</cite></a></dd>
                        <dd><a href="javascript:;" data-url="/User/UserChagePwd"><i class="seraph icon-xiugai" data-icon="icon-xiugai"></i><cite>修改密码</cite></a></dd>
                        <dd><a href="/User/Login" class="signOut"><i class="seraph icon-tuichu"></i><cite>退出</cite></a></dd>
                    </dl>
                </li>
            </ul>
        </div>
    </div>
    <!-- 左侧导航 -->
    <div class="layui-side layui-bg-black">
        <div class="user-photo">
            <a class="img" title="我的头像"><img src="@Model.UserAvatar" class="userAvatar"></a>
            <p>您好！<span class="userName">@Model.UserNikeName</span>, 欢迎登录</p>
        </div>
        @*<div class="navbar layui-side-scroll" id="navbar">
                <ul class="layui-nav layui-nav-tree">
                    <li class="layui-nav-item layui-this">
                        <a href="javascript:;" data-url="/home/welcome"><i class="layui-icon" data-icon=""></i><cite>后台首页</cite></a>
                    </li>
                    <li class="layui-nav-item ">
                        <a href="javascript:;" data-url="/home/welcome"><i class="layui-icon" data-icon=""></i><cite>后台首页</cite></a>
                    </li>
                    <li class="layui-nav-item ">
                        <a href="javascript:;" data-url="/home/welcome"><i class="layui-icon" data-icon=""></i><cite>后台首页</cite></a>
                    </li>
                </ul>
            </div>*@
        <div class="left-nav">
            <div id="side-nav">
                @await Component.InvokeAsync("Navigation")
                @*<ul id="nav">
                        <li>
                            <a href="javascript:;">
                                <i class="iconfont">&#xe6b8;</i>
                                <cite>会员管理</cite>
                                <i class="iconfont nav_right">&#xe697;</i>
                            </a>
                            <ul class="sub-menu">
                                <li>
                                    <a _href="member-list.html">
                                        <i class="iconfont">&#xe6a7;</i>
                                        <cite>会员列表</cite>

                                    </a>
                                </li>
                                <li>
                                    <a _href="member-del.html">
                                        <i class="iconfont">&#xe6a7;</i>
                                        <cite>会员删除</cite>

                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:;">
                                        <i class="iconfont">&#xe70b;</i>
                                        <cite>会员管理</cite>
                                        <i class="iconfont nav_right">&#xe697;</i>
                                    </a>
                                    <ul class="sub-menu">
                                        <li>
                                            <a _href="xxx.html">
                                                <i class="iconfont">&#xe6a7;</i>
                                                <cite>会员列表</cite>

                                            </a>
                                        </li>
                                        <li>
                                            <a _href="xx.html">
                                                <i class="iconfont">&#xe6a7;</i>
                                                <cite>会员删除</cite>

                                            </a>
                                        </li>
                                        <li>
                                            <a _href="xx.html">
                                                <i class="iconfont">&#xe6a7;</i>
                                                <cite>等级管理</cite>

                                            </a>
                                        </li>

                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="javascript:;">
                                <i class="iconfont">&#xe723;</i>
                                <cite>订单管理</cite>
                                <i class="iconfont nav_right">&#xe697;</i>
                            </a>
                            <ul class="sub-menu">
                                <li>
                                    <a _href="order-list.html">
                                        <i class="iconfont">&#xe6a7;</i>
                                        <cite>订单列表</cite>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="javascript:;">
                                <i class="iconfont">&#xe726;</i>
                                <cite>管理员管理</cite>
                                <i class="iconfont nav_right">&#xe697;</i>
                            </a>
                            <ul class="sub-menu">
                                <li>
                                    <a _href="admin-list.html">
                                        <i class="iconfont">&#xe6a7;</i>
                                        <cite>管理员列表</cite>
                                    </a>
                                </li>
                                <li>
                                    <a _href="admin-role.html">
                                        <i class="iconfont">&#xe6a7;</i>
                                        <cite>角色管理</cite>
                                    </a>
                                </li>
                                <li>
                                    <a _href="admin-cate.html">
                                        <i class="iconfont">&#xe6a7;</i>
                                        <cite>权限分类</cite>
                                    </a>
                                </li>
                                <li>
                                    <a _href="admin-rule.html">
                                        <i class="iconfont">&#xe6a7;</i>
                                        <cite>权限管理</cite>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>*@
            </div>
        </div>
    </div>
    <!-- 右侧内容 -->
    <div class="layui-body layui-form">
        <div class="layui-tab mag0" lay-filter="bodyTab" lay-allowClose="true" id="top_tabs_box" style="margin-top:0px;">
            <ul class="layui-tab-title top_tab" id="top_tabs">
                <li class="layui-this" lay-id=""><i class="layui-icon">&#xe68e;</i><cite id="houtaihome">后台首页</cite></li>
            </ul>
            <ul class="layui-nav closeBox">
                <li class="layui-nav-item">
                    <a href="javascript:;"><i class="layui-icon caozuo">&#xe643;</i> 页面操作</a>
                    <dl class="layui-nav-child">
                        <dd><a href="javascript:;" class="refresh refreshThis"><i class="layui-icon">&#x1002;</i> 刷新当前</a></dd>
                        <dd><a href="javascript:;" class="closePageOther"><i class="seraph icon-prohibit"></i> 关闭其他</a></dd>
                        <dd><a href="javascript:;" class="closePageAll"><i class="seraph icon-guanbi"></i> 关闭全部</a></dd>
                    </dl>
                </li>
            </ul>
            <div class="layui-tab-content clildFrame">
                <div class="layui-tab-item layui-show">
                    <iframe src="/Home/Welcome"></iframe>
                </div>
            </div>
        </div>
    </div>
    <!-- 底部 -->
    <div class="layui-footer footer">
        <p><span style="color: black;">copyright 2018 作者:周黎</span>
    </div>
</div>
<!-- 移动导航 -->
<div class="site-tree-mobile"><i class="layui-icon">&#xe602;</i></div>
<div class="site-mobile-shade"></div>

ZhouliProject/ZhouliSystem/Views/Home/welcome.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>主页</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta http-equiv="Access-Control-Allow-Origin" content="*">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">
</head>
<body >
   主页-欢迎您
</body>
</html>